/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionRouteImport } from './routes/solution'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const SolutionRoute = SolutionRouteImport.update({
  id: '/solution',
  path: '/solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/demo': typeof DemoRoute
  '/metrics': typeof MetricsRoute
  '/problem': typeof ProblemRoute
  '/solution': typeof SolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/demo': typeof DemoRoute
  '/metrics': typeof MetricsRoute
  '/problem': typeof ProblemRoute
  '/solution': typeof SolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/demo': typeof DemoRoute
  '/metrics': typeof MetricsRoute
  '/problem': typeof ProblemRoute
  '/solution': typeof SolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/demo'
    | '/metrics'
    | '/problem'
    | '/solution'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/architecture' | '/demo' | '/metrics' | '/problem' | '/solution'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/demo'
    | '/metrics'
    | '/problem'
    | '/solution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DemoRoute: typeof DemoRoute
  MetricsRoute: typeof MetricsRoute
  ProblemRoute: typeof ProblemRoute
  SolutionRoute: typeof SolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solution': {
      id: '/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof SolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DemoRoute: DemoRoute,
  MetricsRoute: MetricsRoute,
  ProblemRoute: ProblemRoute,
  SolutionRoute: SolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
